module.exports = {
	AuthControllers: require("./controller.auth"),
	DivisiControllers: require("./controller.divisi"),
	FileControllers: require("./controller.file"),
	GolonganControllers: require("./controller.golongan"),
	InstansiControllers: require("./controller.instansi"),
	JabatanControllers: require("./controller.jabatan"),
	MutasiControllers: require("./controller.mutasi"),
	NotFoundControllers: require("./controller.404"),
	PegawaiControllers: require("./controller.pegawai"),
	PendidikanControllers: require("./controller.pendidikan"),
	ProfilControllers: require("./controller.profil"),
	ResetPasswordControllers: require("./controller.resetPassword"),
	StatusPegawaiControllers: require("./controller.statusPegawai"),
	TipePegawaiControllers: require("./controller.tipePegawai"),
};
