module.exports = {
	AkunServices: require("./service.akun"),
	AuthServices: require("./service.auth"),
	ClaimsServices: require("./service.claims"),
	CutiServices: require("./service.cuti"),
	DataPribadiServices: require("./service.dataPribadi"),
	DivisiServices: require("./service.divisi"),
	DokumenServices: require("./service.dokumen"),
	FileServices: require("./service.file"),
	GolonganServices: require("./service.golongan"),
	InstansiServices: require("./service.instansi"),
	JabatanServices: require("./service.jabatan"),
	MutasiServices: require("./service.mutasi"),
	PegawaiServices: require("./service.pegawai"),
	PendidikanServices: require("./service.pendidikan"),
	StatusPegawaiServices: require("./service.statusPegawai"),
	TipePegawaiServices: require("./service.tipePegawai"),
};
