module.exports = {
	AuthServices: require("./service.auth"),
	TipePegawaiServices: require("./service.tipePegawai"),
	StatusPegawaiServices: require("./service.statusPegawai"),
	InstansiServices: require("./service.instansi"),
	DivisiServices: require("./service.divisi"),
	JabatanServices: require("./service.jabatan"),
	GolonganServices: require("./service.golongan"),
	PegawaiServices: require("./service.pegawai"),
	DataPribadiServices: require("./service.dataPribadi"),
	PendidikanServices: require("./service.pendidikan"),
	DokumenServices: require("./service.dokumen"),
	FileServices: require("./service.file"),
	AkunServices: require("./service.akun"),
	ClaimsServices: require("./service.claims"),
};
